### PR TITLE
core/generator: handle commit block failures

### LINKED ISSUE #1034: core/generator: restart required after failed signature
While testing #1033, I accidentally misconfigured the signer node and didn't make it a signer. As expected that signer node 404'd when the generator called its sign-block RPC:

```
app=cored buildtag=? processID=chain-mba.local-40952-b596e957c19e3cf194cc at=block.go:147 t=2017-04-24T22:22:49.330034662Z error="Request to `http://localhost:1999/rpc/signer/sign-block` responded with 404 Not Found" signer=http://localhost:1999
/Users/jackson/src/chain/log/log.go:143 - chain/log.Printkv
/Users/jackson/src/chain/core/generator/block.go:147 - chain/core/generator.getSig
/usr/local/go/src/runtime/asm_amd64.s:2197 - runtime.goexit
app=cored buildtag=? processID=chain-mba.local-40952-b596e957c19e3cf194cc at=generator.go:132 t=2017-04-24T22:22:49.330196251Z error="sign: got 1 of 2 needed signatures"
/Users/jackson/src/chain/core/generator/block.go:70 - chain/core/generator.(*Generator).commitBlock
/Users/jackson/src/chain/core/generator/block.go:64 - chain/core/generator.(*Generator).makeBlock
/Users/jackson/src/chain/core/generator/generator.go:129 - chain/core/generator.(*Generator).Generate
/usr/local/go/src/runtime/asm_amd64.s:2197 - runtime.goexit
```

However, after reconfiguring and restarting the signer, the generator never attempted to get the block signature again. It was stuck at that height with a block saved in the postgres `generator_pending_block` table. Restarting the generator fixed the problem.

Looking at the code, it looks like a failed call to `g.commitBlock` will bubble the error up to [the main generator loop](https://github.com/chain/chain/blob/main/core/generator/generator.go#L132) where it gets logged. On the next tick, it'll try to create a new block (instead of using the previously persisted pending block).

### PR DESCRIPTION
**Pull request by jbowens**
Handle failures to commit blocks gracefully. Previously, the generator
could get stuck requiring a restart to make progress.

Fix #1034.

### CODE REVIEW

**Comment by jbowens** [comment]
PTAL

Any suggestions on how to create a 1-of-1 signature Chain? I did something gross by yolo-committing a new block with a custom consensus program. Maybe prottest could have a way to configure this type of thing?

**Comment by kr** [comment]
:eyes:

**Comment by jbowens** [comment]
Updated with new prottest Option, PTAL

**Comment by kr** [comment]
:eyes:

File: protocol/prottest/block.go [hunk 1]
```diff
@@ -15,27 +16,46 @@ import (
...
 			conf.initialState.Tree.Insert(oid.Bytes())
 		}
 	}
 }
 
+func WithBlockSigners(quorum, n int) Option {
+	return func(tb testing.TB, conf *config) {
+		conf.quorum = quorum
+		for i := 0; i < n; i++ {
+			pubkey, privkey, err := ed25519.GenerateKey(nil)
```
Comment (kr) [inline protocol/prottest/block.go]: It is a minor bummer that GenerateKey doesn't just panic if it can't get randomness.

**Comment by kr** [comment]
LGTM
