### PR TITLE
sdk/java: make sdk Java 1.7 compliant

### LINKED ISSUE #187: Make Java SDK 1.7 compliant
#### Environment 
1. Chain Core Version: latest
2. Chain Core SDK Language and Version: Java latest 
3. Host: Docker on linux

#### Issue
To achieve a more broad usage of the Java SDK it would be nice to make it Java 7 compliant.
I've downloaded the source code and there are a few steps to convert the SDK to Java 7.

1. com.chain.http.Client -> remove lambdas (just create 3 inner classes o anonymous classes)
2. com.chain.api.PagedItems -> implement the remove method (the Java 8 default is throwing a UnsupportedOperationException("remove"))
3. com.chain.signing.HsmSigner.addKey(String, Client) -> add type String to new ArrayList<>

### PR DESCRIPTION
**Pull request by boymanjor**
Fixes #187

### CODE REVIEW

**Comment by boymanjor** [comment]
@jeffomatic PTAL

**Comment by jeffomatic** [comment]
👀

File: sdk/java/src/main/java/com/chain/api/PagedItems.java [hunk 1]
```diff
@@ -105,4 +112,15 @@ public boolean hasNext() {
       }
     }
   }
+
+  /**
+   * Removes the last element returned by {@link PagedItems#next()} from the underlying collection.
+   */
+  public void remove() throws IllegalStateException {
+    if (!canRemove) {
```
Comment (jeffomatic) [inline sdk/java/src/main/java/com/chain/api/PagedItems.java]: TL;DR we should consider simplifying this function to `throw UnsupportedOperationException`.

According to the [Java 7 docs](https://docs.oracle.com/javase/7/docs/api/java/util/Iterator.html), it is perfectly fine to implement this method by throwing `UnsupportedOperationException`. For our case, I believe this is the more appropriate behavior. `remove` makes sense if the iterator object refers back to a collection that the user interacts with directly. In other words, it seems to be appropriate for this type of situation:

```
Collection c;
Iterator i = c.iterator();
while (i.hasNext()) {
  Object o = i.next();
  if (shouldRemove(0)) {
    i.remove();
  }
}

// Now collection c is updated.
```

However, I believe `PagedItems` works a bit differently. While there is an underlying `List<T>`, we don't really encourage using that list directly. Calling `remove` on a `PagedItems` object is a weird use case.

Moreover, it may be better for us to make `list` a protected member, so that users are not tempted to use it directly.

File: sdk/java/src/main/java/com/chain/http/Client.java [hunk 2]
```diff
@@ -141,13 +143,15 @@ public Client(URL url, String accessToken) {
...
-        action,
-        body,
-        (Response response, Gson deserializer) ->
-            new BatchResponse(response, deserializer, tClass, eClass));
+  public <T> BatchResponse<T> batchRequest(
+      String action, Object body, final Type tClass, final Type eClass) throws ChainException {
+    ResponseCreator<T> rc =
+        new ResponseCreator<T>() {
+          public T create(Response response, Gson deserializer) throws ChainException, IOException {
+            return (T) new BatchResponse<T>(response, deserializer, tClass, eClass);
```
Comment (jeffomatic) [inline sdk/java/src/main/java/com/chain/http/Client.java]: Does this actually work at runtime? There appear to be two competing meanings of the generic specifier `T` in this method.

1. The type of the object returned by the ResponseCreator lambda class. In this case, it should be `ResponseCreator<BatchResponse<T>>`
2. The type of the object contained in the `BatchResponse` generic class.

My assumption would be that the code in the PR will break at runtime, but this might work:

```
ResponseCreator<BatchResponse<T>> rc =
        new ResponseCreator<BatchResponse<T>>() {
          public BatchResponse<T> create(Response response, Gson deserializer) throws ChainException, IOException {
            return new BatchResponse<T>(response, deserializer, tClass, eClass);
          }
        }
```

File: sdk/java/src/main/java/com/chain/api/PagedItems.java (hunk 1 above)
Comment (boymanjor) [inline sdk/java/src/main/java/com/chain/api/PagedItems.java]: I'll definitely buy this. I'll implement `remove` as stated above.

File: sdk/java/src/main/java/com/chain/http/Client.java (hunk 2 above)
Comment (boymanjor) [inline sdk/java/src/main/java/com/chain/http/Client.java]: This does work at runtime, but your suggested changes add clarity to the code. I'll update.

**Comment by boymanjor** [comment]
updated, PTAL

**Comment by fcanevar** [comment]
Hi! Thanks for updating the SDK. Do you know when will it be available through the website?
